files:
  - source: /romfs/lang/en/app.json
    translation: /romfs/lang/%two_letters_code%/app.json
  - source: /romfs/lang/fr/app.json
    translation: /romfs/lang/%two_letters_code%/app.json
  - source: /romfs/lang/es/app.json
    translation: /romfs/lang/%two_letters_code%/app.json
